//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeabirdsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cruise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cruise()
        {
            this.Observations = new HashSet<Observation>();
            this.Shipboards = new HashSet<Shipboard>();
        }
    
        public int CruiseID { get; internal set; }
        public string CruiseRef { get; set; }
        public Nullable<int> VesselID { get; set; }
        public string PortLeave { get; set; }
        public string PortReturn { get; set; }
        public Nullable<System.DateTime> DateLeave { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public System.DateTime InsertTimeStamp { get; internal set; }
    
        internal virtual Vessel Vessel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Observation> Observations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Shipboard> Shipboards { get; set; }
    }
}
