//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeabirdsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public int ObservationID { get; internal set; }
        public Nullable<int> CruiseID { get; set; }
        public Nullable<int> TransectID { get; set; }
        public Nullable<int> SpeciesID { get; set; }
        public string Present { get; set; }
        public Nullable<int> Flying { get; set; }
        public Nullable<int> Sitting { get; set; }
        public System.DateTime InsertTimeStamp { get; internal set; }
    
        internal virtual Cruise Cruise { get; set; }
        internal virtual Species Species { get; set; }
        internal virtual Transect Transect { get; set; }
    }
}
