
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SeabirdsAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Observer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Observer()
    {

        this.Shipboards = new HashSet<Shipboard>();

        this.Transects = new HashSet<Transect>();

        this.Transects1 = new HashSet<Transect>();

    }


    public int ObserverID { get; internal set; }

    public string Fullname { get; set; }

    public string Experience { get; set; }

    public System.DateTime InsertTimeStamp { get; internal set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    internal virtual ICollection<Shipboard> Shipboards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    internal virtual ICollection<Transect> Transects { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    internal virtual ICollection<Transect> Transects1 { get; set; }

}

}
