
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SeabirdsAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Shipboard
{

    public int ID { get; internal set; }

    public int CruiseID { get; set; }

    public Nullable<int> ObserverID { get; set; }

    public Nullable<int> ObserverNo { get; set; }

    public string ShipDuty { get; set; }

    public Nullable<System.DateTime> InsertTimeStamp { get; internal set; }



    internal virtual Cruise Cruise { get; set; }

    internal virtual Observer Observer { get; set; }

}

}
