//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeabirdsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Species()
        {
            this.Observations = new HashSet<Observation>();
        }
    
        public int SpeciesID { get; internal set; }
        public Nullable<int> SAFRING_No { get; set; }
        public string Taxonomic_Genus { get; set; }
        public string Taxonomic_Species { get; set; }
        public string English_Genus { get; set; }
        public string English_Species { get; set; }
        internal Nullable<double> Old { get; set; }
        public string Taxon_order { get; set; }
        public string Taxon_family { get; set; }
        public string Taxon_group { get; set; }
        public string Continent { get; set; }
        public string Region { get; set; }
        public string Notes { get; set; }
        public string Project { get; set; }
        public string LegendColor { get; set; }
        public string FamilyName { get; set; }
        public string BirdLifeID { get; set; }
        public string IUCNRedListCat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Observation> Observations { get; set; }
    }
}
