
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SeabirdsAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transect
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transect()
    {

        this.Observations = new HashSet<Observation>();

    }


    public int TransectID { get; internal set; }

    public string TransectRef { get; set; }

    public Nullable<int> CruiseID { get; set; }

    internal Nullable<int> DataSourceID { get; set; }

    public string TransectNo { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<System.DateTime> TimeStart { get; set; }

    public Nullable<System.DateTime> TimeEnd { get; set; }

    public Nullable<int> Observer1ID { get; set; }

    public Nullable<int> Observer2ID { get; set; }

    public string CountType { get; set; }

    public string WindDirection { get; set; }

    public Nullable<double> WindDirection_deg { get; set; }

    public string WindStrength_kmph { get; set; }

    public string CloudCover { get; set; }

    public string Visibility_m { get; set; }

    public string Precipitation { get; set; }

    public string CountingShipFollowers { get; set; }

    public Nullable<double> SwellHeight_m { get; set; }

    public string CoordinateSystem { get; set; }

    public Nullable<double> LatitudeStart { get; set; }

    public Nullable<double> LongitudeStart { get; set; }

    public Nullable<double> LatitudeEnd { get; set; }

    public Nullable<double> LongitudeEnd { get; set; }

    public Nullable<int> CountArea { get; set; }

    public Nullable<int> ArcFromBow { get; set; }

    public string PositionOnVessel { get; set; }

    public System.DateTime InsertTimeStamp { get; internal set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    internal virtual ICollection<Observation> Observations { get; set; }

    internal virtual Observer Observer { get; set; }

    internal virtual Observer Observer1 { get; set; }

}

}
